### ISSUE TITLE
ASTLine.data bug

### ISSUE THREAD

**Issue by jxw1102** [jxw1102/Projet-merou#1]
Old implementation: use Regex ```"0x[\\dabcdef]{9} <.+> (.*)"``` to match *data*;
Bug: ```<<<NULL>>>``` can not be recognised, all **NullASTNode** become **OtherASTNode**
New implementation: ```def data = s.substring(indent)```
Stop abusing the Regex!

**Comment by Dicee** [comment]
Ok, fine. I'll use yout version.
