### ISSUE TITLE
AU et EU du model checking

### ISSUE THREAD

**Issue by azsm** [jxw1102/Projet-merou#5]
En testant le AU et le EU du model checking: Il y a un problème avec l'algorithme puisque le code n'est que la repésentation littérale de l'algo

A revoir d'urgence, sinon on doit envoyer un mail au prof.

Parce que en executant l'algo, le conj va toujours renvoyer un Set() si les deux prédicats ne sont pas réalisés de suite.

**Comment by Dicee** [comment]
C'est à cause du test if (!x.isEmpty) ?
